name: Node Continuous Integration
on: push
jobs:
  build-node:
    name: Build Node
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Check Node Version
        run: node --version
      - name: Check NPM Version
        run: npm --version
      - name: Chckeout Code
        uses: actions/checkout@v4
      - name: Install NPM Packages
        run: npm install
      - name: Run Application
        run: node app.js
        